version: '2'


services:
    nginx:
        image: tutum/nginx
        ports:
            - "80:80"
        links:
            - phpfpm
        volumes:
            - ./build/default:/etc/nginx/sites-available/default
            - ./build/default:/etc/nginx/sites-enabled/default
    phpfpm:
        image: php:fpm
        ports:
            - "9000:9000"
        volumes:
            - ./:/usr/share/nginx/html
    mysql:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - "3306:3306" 
