version: "2.4"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      php:
        condition: service_started
    volumes:
        - ./opt/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        - ./public:/var/www/html/public

  php:
    build:
      target: dev
      context: .
    working_dir: /var/www/html
    volumes:
        - .:/var/www/html:z
