name: Push to GitHub Pages on push to master
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.59.1
          TARGET_REPO: JohnstonCode/johnstoncode.github.io
          TOKEN: ${{ secrets.TOKEN }}
          HUGO_ARGS: ''
          CNAME: chrisjohnston.co.uk